using System.IO;
using CorpusSearch.Dependencies.Lucene;
using NUnit.Framework;

namespace CorpusSearch.Test;

/// <summary>
/// The resolution artifacts' contract (lemma.overrides.tsv / lemma.sidecar.tsv,
/// generated by the LemmaAdjudication harness): hashing, parsing, and the rule
/// that a resolution must strictly narrow the table's candidate set.
/// </summary>
[TestFixture]
public class LemmaResolverTest
{
    private static LemmaTable Table(params string[] rows)
    {
        var tsv = "form\tlemmaId\tlemma\tlinkType\tpos\tvia\tnote\n" + string.Join("\n", rows);
        using var reader = new StringReader(tsv);
        return LemmaTable.Load(reader);
    }

    private static string Row(string form, string lemmaId) => $"{form}\t{lemmaId}\tx\tself\tx\t{form}\t";

    private static LemmaResolver Load(LemmaTable table, string? overrides = null, string? sidecar = null)
    {
        return LemmaResolver.Load(
            overrides == null ? null : new StringReader(overrides),
            sidecar == null ? null : new StringReader(sidecar),
            table);
    }

    private static readonly LemmaTable Ambiguous = Table(
        Row("veg", "veg.x"), Row("veg", "beg.a"),
        Row("er", "er.x"), Row("er", "fer.n"),
        Row("moddey", "moddey.n"));

    /// <summary>Pins the artifact hash format (first 16 hex of SHA-256 over the
    /// space-joined token stream): a change here orphans every sidecar row</summary>
    [Test]
    public void TheLineKeyMatchesTheArtifactContract()
    {
        Assert.That(LemmaResolver.Hash("ta mee"), Is.EqualTo("9c500fb9a21e2a50"));
        Assert.That(LemmaResolver.LineKey(["ta", "mee"]), Is.EqualTo("9c500fb9a21e2a50"));
    }

    /// <summary>The key's token stream is the manx_lemma pipeline's: uncased,
    /// punctuation-split, hyphens and apostrophes word-internal</summary>
    [Test]
    public void TokenizeManxMatchesTheIndexPipeline()
    {
        Assert.That(LemmaResolver.TokenizeManx("Ta mee, dy-jarroo!"),
            Is.EqualTo(new[] { "ta", "mee", "dy-jarroo" }));
    }

    [Test]
    public void OverridesSkipCommentsAndTheHeader()
    {
        var resolver = Load(Ambiguous, overrides: "# a comment\nform\tlemmaIds\tudEvidence\ner\ter.x\t12/12\n");

        Assert.That(resolver.OverrideFor("er"), Is.EqualTo(new[] { "er.x" }));
        // the lookup normalizes its input, like every table lookup
        Assert.That(resolver.OverrideFor("Er"), Is.EqualTo(new[] { "er.x" }));
        Assert.That(resolver.OverrideFor("veg"), Is.Null);
    }

    /// <summary>Rows that don't strictly narrow the table's candidates can only be
    /// version skew between the artifacts and the table: dropped, never applied</summary>
    [Test]
    public void NonNarrowingRowsAreDropped()
    {
        var resolver = Load(Ambiguous, overrides: "form\tlemmaIds\n"
            + "veg\tveg.x,beg.a\n" // the full candidate set: not a resolution
            + "moddey\tmoddey.n\n" // unambiguous form: nothing to narrow
            + "er\ter.x,gone.x\n" // an id the table no longer has for the form
            + "xyzzy\tfoo.x\n"); // a form the table doesn't know

        Assert.That(resolver.OverrideFor("veg"), Is.Null);
        Assert.That(resolver.OverrideFor("moddey"), Is.Null);
        Assert.That(resolver.OverrideFor("er"), Is.Null);
        Assert.That(resolver.OverrideFor("xyzzy"), Is.Null);
    }

    [Test]
    public void SidecarRowsGateOnTheirTier()
    {
        var resolver = Load(Ambiguous, sidecar: "docId\tkey\tenglishHash\ttokenIndex\tform\tlemmaIds\ttier\thumanVerified\n"
            + "doc\tkey1\thash\t0\tveg\tveg.x\tindex\t0\n"
            + "doc\tkey2\thash\t3\ter\ter.x\tpopup\t0\n");

        // index tier: search index and popup both see it
        Assert.That(resolver.SidecarFor("key1", 0, "veg", includePopupTier: false), Is.EqualTo(new[] { "veg.x" }));
        Assert.That(resolver.SidecarFor("key1", 0, "veg", includePopupTier: true), Is.EqualTo(new[] { "veg.x" }));
        // popup tier: display demotion only
        Assert.That(resolver.SidecarFor("key2", 3, "er", includePopupTier: false), Is.Null);
        Assert.That(resolver.SidecarFor("key2", 3, "er", includePopupTier: true), Is.EqualTo(new[] { "er.x" }));
        // a key or index without a row
        Assert.That(resolver.SidecarFor("key1", 1, "veg", includePopupTier: true), Is.Null);
        Assert.That(resolver.SidecarFor("other", 0, "veg", includePopupTier: true), Is.Null);
    }

    [Test]
    public void ASidecarRowOnlyAppliesToItsOwnForm()
    {
        var resolver = Load(Ambiguous, sidecar: "docId\tkey\tenglishHash\ttokenIndex\tform\tlemmaIds\ttier\thumanVerified\n"
            + "doc\tkey1\thash\t0\tveg\tveg.x\tindex\t0\n");

        Assert.That(resolver.SidecarFor("key1", 0, "er", includePopupTier: true), Is.Null);
    }

    [Test]
    public void NoArtifactsMeansNoResolutions()
    {
        var resolver = LemmaResolver.Load(null, null, Ambiguous);

        Assert.That(resolver.HasSidecarRows, Is.False);
        Assert.That(resolver.OverrideFor("veg"), Is.Null);
        Assert.That(LemmaResolver.Empty.HasSidecarRows, Is.False);
    }
}
