# Deploying the latest image on the server:
#  docker compose up -d
#
# Building locally (dev): 
#  uncomment `build:` then: 
#  docker compose up -d --build
services:
  corpus-search:
    image: "ghcr.io/david-allison/manx-corpus-search:master"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: corpus-search
    restart: unless-stopped
    ports:
      - "127.0.0.1:5002:8080" # proxied by nginx
    # no logs; for user privacy
    logging:
      driver: "none"

  # Auto-updates the app from https://github.com/david-allison/manx-corpus-search
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup