using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Lucene.Net.Analysis.TokenAttributes;
using Lucene.Net.Util;

namespace CorpusSearch.Dependencies.Lucene;

/// <summary>
/// The lemma disambiguation layers (manx-lemma-data artifacts, generated by
/// the CorpusSearch.Test/LemmaAdjudication harness). A resolution only ever
/// narrows a form's candidate set — every resolved id is one of the table's
/// candidates — and any miss falls back to the full set, so a stale or absent
/// file can't hide a reading the table doesn't already offer.
///
/// - lemma.overrides.tsv (form-level): every occurrence of a form resolves to
///   the given ids, context-free.
/// - lemma.sidecar.tsv (per-line): keyed by (hash of the line's token stream,
///   token index), so any token edit to a line correctly orphans its rows.
///   tier=index rows are high-confidence (search index and popup); tier=popup
///   rows only demote popup readings.
/// </summary>
public class LemmaResolver
{
    private sealed record SidecarRow(string Form, string[] Ids, bool IndexTier);

    private readonly Dictionary<string, string[]> overridesByForm;
    private readonly Dictionary<(string Key, int Index), SidecarRow> sidecarByToken;
    private readonly Dictionary<string, string> equivalenceRoot;

    public static readonly LemmaResolver Empty = new([], [], []);

    // read once, shared by the index-time analyzer and the popup
    private static readonly Lazy<LemmaResolver> Lazy = new(LoadVendored);
    public static LemmaResolver Instance => Lazy.Value;

    private LemmaResolver(Dictionary<string, string[]> overridesByForm,
        Dictionary<(string Key, int Index), SidecarRow> sidecarByToken,
        Dictionary<string, string> equivalenceRoot)
    {
        this.overridesByForm = overridesByForm;
        this.sidecarByToken = sidecarByToken;
        this.equivalenceRoot = equivalenceRoot;
    }

    /// <summary>Whether the ids are one lexeme by the equivalence layer's word:
    /// dooys.x and dou.x carry a recorded 'same' verdict (the emphatic and its
    /// base), where goan.a beside goo.n does not. Ids the layer never mentions
    /// are their own lexeme.</summary>
    public bool SameLexeme(IReadOnlyList<string> ids)
    {
        if (ids.Count == 0)
        {
            return false;
        }
        var root = equivalenceRoot.GetValueOrDefault(ids[0], ids[0]);
        for (var i = 1; i < ids.Count; i++)
        {
            if (equivalenceRoot.GetValueOrDefault(ids[i], ids[i]) != root)
            {
                return false;
            }
        }
        return true;
    }

    /// <summary>The form-level resolution of <paramref name="form"/>; null when unresolved</summary>
    public IReadOnlyList<string>? OverrideFor(string form)
    {
        return overridesByForm.TryGetValue(LemmaTable.NormalizeForm(form), out var ids) ? ids : null;
    }

    /// <summary>
    /// The per-line resolution of the token at <paramref name="tokenIndex"/> of the line
    /// hashing to <paramref name="lineKey"/>; null when unresolved. Popup-tier rows are
    /// lower confidence: only returned when <paramref name="includePopupTier"/> is set.
    /// </summary>
    public IReadOnlyList<string>? SidecarFor(string lineKey, int tokenIndex, string form, bool includePopupTier)
    {
        if (!sidecarByToken.TryGetValue((lineKey, tokenIndex), out var row)
            || (!row.IndexTier && !includePopupTier))
        {
            return null;
        }
        // the key already pins the token stream; the form check guards row corruption
        return row.Form == form ? row.Ids : null;
    }

    /// <summary>Whether any per-line rows exist: gates the token filter's buffering</summary>
    public bool HasSidecarRows => sidecarByToken.Count > 0;

    /// <summary>First 16 hex characters of SHA-256(UTF-8): the artifacts' hash format</summary>
    public static string Hash(string text)
    {
        return Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(text)))[..16];
    }

    /// <summary>The sidecar's line key: a hash of the line's space-joined token stream</summary>
    public static string LineKey(IEnumerable<string> streamTokens)
    {
        return Hash(string.Join(" ", streamTokens));
    }

    /// <summary>The manx_lemma pipeline's tokens (uncased ManxTokenizer + ManxTokenFilter):
    /// the stream <see cref="LineKey(IEnumerable{string})"/> is computed over</summary>
    public static List<string> TokenizeManx(string text)
    {
        var result = new List<string>();
        var tokenizer = new ManxTokenizer(LuceneVersion.LUCENE_48, new StringReader(text));
        using var stream = new ManxTokenFilter(tokenizer);
        var term = stream.GetAttribute<ICharTermAttribute>();
        stream.Reset();
        while (stream.IncrementToken())
        {
            result.Add(term.ToString());
        }
        stream.End();
        return result;
    }

    /// <summary>
    /// Reads the artifacts (either reader may be null). Rows whose ids are not a strict,
    /// non-empty subset of the table's candidates for their form are dropped: they can
    /// only mean version skew between the table and the artifacts.
    /// </summary>
    public static LemmaResolver Load(TextReader? overrides, TextReader? sidecar, LemmaTable table,
        TextReader? equivalences = null)
    {
        var dropped = 0;

        string[]? Narrowing(string form, string idsColumn)
        {
            var ids = idsColumn.Split(',');
            var candidates = table.CandidatesFor(form);
            if (ids.Length == 0 || ids.Length >= candidates.Count || !ids.All(candidates.Contains))
            {
                dropped++;
                return null;
            }
            return ids;
        }

        // form \t lemmaIds \t evidence…
        var overridesByForm = new Dictionary<string, string[]>();
        foreach (var columns in Rows(overrides, headerPrefix: "form\t"))
        {
            if (columns.Length < 2)
            {
                continue;
            }
            var ids = Narrowing(columns[0], columns[1]);
            if (ids != null)
            {
                overridesByForm[LemmaTable.NormalizeForm(columns[0])] = ids;
            }
        }

        // docId \t key \t englishHash \t tokenIndex \t form \t lemmaIds \t tier \t humanVerified
        // (englishHash is a data-side staleness marker; humanVerified doesn't change behaviour)
        var sidecarByToken = new Dictionary<(string, int), SidecarRow>();
        foreach (var columns in Rows(sidecar, headerPrefix: "docId\t"))
        {
            if (columns.Length < 7 || !int.TryParse(columns[3], out var tokenIndex))
            {
                continue;
            }
            var ids = Narrowing(columns[4], columns[5]);
            if (ids != null)
            {
                sidecarByToken[(columns[1], tokenIndex)] = new SidecarRow(columns[4], ids, columns[6] == "index");
            }
        }

        // idA \t idB \t verdict \t note — union over the 'same' verdicts only:
        // the equivalence layer's word for "one lexeme under several headwords"
        var equivalenceRoot = new Dictionary<string, string>();
        string Find(string id)
        {
            if (!equivalenceRoot.TryGetValue(id, out var p) || p == id)
            {
                return id;
            }
            var root = Find(p);
            equivalenceRoot[id] = root;
            return root;
        }
        foreach (var columns in Rows(equivalences, headerPrefix: "idA\t"))
        {
            if (columns.Length < 3 || columns[2] != "same")
            {
                continue;
            }
            var (a, b) = (Find(columns[0]), Find(columns[1]));
            if (a != b)
            {
                equivalenceRoot[a] = b;
            }
        }
        foreach (var id in equivalenceRoot.Keys.ToList())
        {
            equivalenceRoot[id] = Find(id);
        }

        if (overridesByForm.Count > 0 || sidecarByToken.Count > 0 || dropped > 0)
        {
            Serilog.Log.Information(
                "Lemma resolutions: {Overrides} form overrides, {Sidecar} sidecar rows, {Equivalences} equivalence-linked ids ({Dropped} dropped as not narrowing the table's candidates)",
                overridesByForm.Count, sidecarByToken.Count, equivalenceRoot.Count, dropped);
        }
        return new LemmaResolver(overridesByForm, sidecarByToken, equivalenceRoot);
    }

    private static IEnumerable<string[]> Rows(TextReader? reader, string headerPrefix)
    {
        if (reader == null)
        {
            yield break;
        }
        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0 || line.StartsWith('#') || line.StartsWith(headerPrefix))
            {
                continue;
            }
            yield return line.Split('\t');
        }
    }

    private static LemmaResolver LoadVendored()
    {
        // absent until the data side adopts the artifacts: candidate sets stay fully ambiguous
        using var overrides = OpenOptional("lemma.overrides.tsv");
        using var sidecar = OpenOptional("lemma.sidecar.tsv");
        using var equivalences = OpenOptional("lemma.equivalences.seed.tsv");
        return overrides == null && sidecar == null && equivalences == null
            ? Empty
            : Load(overrides, sidecar, LemmaTable.Instance, equivalences);

        static TextReader? OpenOptional(string name)
        {
            var path = Startup.GetLocalFile("Resources", name);
            return File.Exists(path) ? new StreamReader(path) : null;
        }
    }
}
